### ISSUE TITLE
./list_servers error

### ISSUE THREAD

**Issue by xman0980** [hongkongkiwi/privado-wireguard-vpn#1]
In case anyone finds this script, the list_servers file needs a quick edit.

its missing this line

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

Just add it below #!/bin/bash -ue 

Other than that, this set of scripts works as of 2024/5/9

**Comment by hongkongkiwi** [comment]
Thanks! I've just added your change.

Feel free to add any additional pull requests if you like.
