### ISSUE TITLE
Wireguard configs available on privado web site

### ISSUE THREAD

**Issue by timma-gen** [hongkongkiwi/privado-wireguard-vpn#2]
This is a cool project, but when I login to the privado web interface (https://app.privadovpn.com/en/admin-panel), there's a Manual Configuration section that allows you to generate and download OpenVPN configs or wireguard configs.  Is that not available to you?  I'm coming from the US -- perhaps this is geo-restricted?

**Comment by hongkongkiwi** [comment]
That's great. At the time I wrote this project Wireguard configs were not available from their website.

Similar to other VPN services like Nord you could only use them via the client.

It may be they have added this recently, OR it may be this feature wasn't available as I was using a free account provided as part of a Usenet provider offering.

If using their web config works for you it's definitely a better option than using these scripts. Mostly this was a weekend hack for my own use.

**Comment by hongkongkiwi** [comment]
Your right, just checked I can access Wireguard configs now, so this tool is probably redundant. I'll add a comment and archive it.
